using System.ComponentModel;

namespace OmiLAXR.Enums
{
    public enum Languages
    {
        [Description("Afrikaans")] af ,
        [Description("Afrikaans (South Africa)")] af_ZA,
        [Description("Arabic")] ar,
        [Description("Arabic (U.A.E.)")] ar_AE,
        [Description("Arabic (Bahrain)")] ar_BH,
        [Description("Arabic (Algeria)")] ar_DZ,
        [Description("Arabic (Egypt)")] ar_EG,
        [Description("Arabic (Iraq)")] ar_IQ,
        [Description("Arabic (Jordan)")] ar_JO,
        [Description("Arabic (Kuwait)")] ar_KW,
        [Description("Arabic (Lebanon)")] ar_LB,
        [Description("Arabic (Libya)")] ar_LY,
        [Description("Arabic (Morocco)")] ar_MA,
        [Description("Arabic (Oman)")] ar_OM,
        [Description("Arabic (Qatar)")] ar_QA,
        [Description("Arabic (Saudi Arabia)")] ar_SA,
        [Description("Arabic (Syria)")] ar_SY,
        [Description("Arabic (Tunisia)")] ar_TN,
        [Description("Arabic (Yemen)")] ar_YE,
        [Description("Azeri (Latin)")] az,
        [Description("Azeri (Latin) (Azerbaijan)")] az_AZ,
        [Description("Azeri (Cyrillic) (Azerbaijan)")] az_Cyrl_AZ,
        [Description("Belarusian")] be,
        [Description("Belarusian (Belarus)")] be_BY,
        [Description("Bulgarian")] bg,
        [Description("Bulgarian (Bulgaria)")] bg_BG,
        [Description("Bosnian (Bosnia and Herzegovina)")] bs_BA,
        [Description("Catalan")] ca,
        [Description("Catalan (Spain)")] ca_ES,
        [Description("Czech")] cs,
        [Description("Czech (Czech Republic)")] cs_CZ,
        [Description("Welsh")] cy,
        [Description("Welsh (United Kingdom)")] cy_GB,
        [Description("Danish")] da,
        [Description("Danish (Denmark)")] da_DK,
        [Description("German")] de,
        [Description("German (Austria)")] de_AT,
        [Description("German (Switzerland)")] de_CH,
        [Description("German (Germany)")] de_DE,
        [Description("German (Liechtenstein)")] de_LI,
        [Description("German (Luxembourg)")] de_LU,
        [Description("Divehi")] dv,
        [Description("Divehi (Maldives)")] dv_MV,
        [Description("Greek")] el,
        [Description("Greek (Greece)")] el_GR,
        [Description("English")] en,
        [Description("English (Australia)")] en_AU,
        [Description("English (Belize)")] en_BZ,
        [Description("English (Canada)")] en_CA,
        [Description("English (Caribbean)")] en_CB,
        [Description("English (United Kingdom)")] en_GB,
        [Description("English (Ireland)")] en_IE,
        [Description("English (Jamaica)")] en_JM,
        [Description("English (New Zealand)")] en_NZ,
        [Description("English (Republic of the Philippines)")] en_PH,
        [Description("English (Trinidad and Tobago)")] en_TT,
        [Description("English (United States)")] en_US,
        [Description("English (South Africa)")] en_ZA,
        [Description("English (Zimbabwe)")] en_ZW,
        [Description("Esperanto")] eo,
        [Description("Spanish")] es,
        [Description("Spanish (Argentina)")] es_AR,
        [Description("Spanish (Bolivia)")] es_BO,
        [Description("Spanish (Chile)")] es_CL,
        [Description("Spanish (Colombia)")] es_CO,
        [Description("Spanish (Costa Rica)")] es_CR,
        [Description("Spanish (Dominican Republic)")] es_DO,
        [Description("Spanish (Ecuador)")] es_EC,
        [Description("Spanish (Spain)")] es_ES,
        [Description("Spanish (Guatemala)")] es_GT,
        [Description("Spanish (Honduras)")] es_HN,
        [Description("Spanish (Mexico)")] es_MX,
        [Description("Spanish (Nicaragua)")] es_NI,
        [Description("Spanish (Panama)")] es_PA,
        [Description("Spanish (Peru)")] es_PE,
        [Description("Spanish (Puerto Rico)")] es_PR,
        [Description("Spanish (Paraguay)")] es_PY,
        [Description("Spanish (El Salvador)")] es_SV,
        [Description("Spanish (Uruguay)")] es_UY,
        [Description("Spanish (Venezuela)")] es_VE,
        [Description("Estonian")] et,
        [Description("Estonian (Estonia)")] et_EE,
        [Description("Basque")] eu,
        [Description("Basque (Spain)")] eu_ES,
        [Description("Farsi")] fa,
        [Description("Farsi (Iran)")] fa_IR,
        [Description("Finnish")] fi,
        [Description("Finnish (Finland)")] fi_FI,
        [Description("Faroese")] fo,
        [Description("Faroese (Faroe Islands)")] fo_FO,
        [Description("French")] fr,
        [Description("French (Belgium)")] fr_BE,
        [Description("French (Canada)")] fr_CA,
        [Description("French (Switzerland)")] fr_CH,
        [Description("French (France)")] fr_FR,
        [Description("French (Luxembourg)")] fr_LU,
        [Description("French (Principality of Monaco)")] fr_MC,
        [Description("Galician")] gl,
        [Description("Galician (Spain)")] gl_ES,
        [Description("Gujarati")] gu,
        [Description("Gujarati (India)")] gu_IN,
        [Description("Hebrew")] he,
        [Description("Hebrew (Israel)")] he_IL,
        [Description("Hindi")] hi,
        [Description("Hindi (India)")] hi_IN,
        [Description("Croatian")] hr,
        [Description("Croatian (Bosnia and Herzegovina)")] hr_BA,
        [Description("Croatian (Croatia)")] hr_HR,
        [Description("Hungarian")] hu,
        [Description("Hungarian (Hungary)")] hu_HU,
        [Description("Armenian")] hy,
        [Description("Armenian (Armenia)")] hy_AM,
        [Description("Indonesian")] id,
        [Description("Indonesian (Indonesia)")] id_ID,
        [Description("Icelandic")] _is,
        [Description("Icelandic (Iceland)")] is_IS,
        [Description("Italian")] it,
        [Description("Italian (Switzerland)")] it_CH,
        [Description("Italian (Italy)")] it_IT,
        [Description("Japanese")] ja,
        [Description("Japanese (Japan)")] ja_JP,
        [Description("Georgian")] ka,
        [Description("Georgian (Georgia)")] ka_GE,
        [Description("Kazakh")] kk,
        [Description("Kazakh (Kazakhstan)")] kk_KZ,
        [Description("Kannada")] kn,
        [Description("Kannada (India)")] kn_IN,
        [Description("Korean")] ko,
        [Description("Korean (Korea)")] ko_KR,
        [Description("Konkani")] kok,
        [Description("Konkani (India)")] kok_IN,
        [Description("Kyrgyz")] ky,
        [Description("Kyrgyz (Kyrgyzstan)")] ky_KG,
        [Description("Lithuanian")] lt,
        [Description("Lithuanian (Lithuania)")] lt_LT,
        [Description("Latvian")] lv,
        [Description("Latvian (Latvia)")] lv_LV,
        [Description("Maori")] mi,
        [Description("Maori (New Zealand)")] mi_NZ,
        [Description("FYRO Macedonian")] mk,
        [Description("FYRO Macedonian (Former Yugoslav Republic of Macedonia)")] mk_MK,
        [Description("Mongolian")] mn,
        [Description("Mongolian (Mongolia)")] mn_MN,
        [Description("Marathi")] mr,
        [Description("Marathi (India)")] mr_IN,
        [Description("Malay")] ms,
        [Description("Malay (Brunei Darussalam)")] ms_BN,
        [Description("Malay (Malaysia)")] ms_MY,
        [Description("Maltese")] mt,
        [Description("Maltese (Malta)")] mt_MT,
        [Description("Norwegian (Bokm?l)")] nb,
        [Description("Norwegian (Bokm?l) (Norway)")] nb_NO,
        [Description("Dutch")] nl,
        [Description("Dutch (Belgium)")] nl_BE,
        [Description("Dutch (Netherlands)")] nl_NL,
        [Description("Norwegian (Nynorsk) (Norway)")] nn_NO,
        [Description("Northern Sotho")] ns,
        [Description("Northern Sotho (South Africa)")] ns_ZA,
        [Description("Punjabi")] pa,
        [Description("Punjabi (India)")] pa_IN,
        [Description("Polish")] pl,
        [Description("Polish (Poland)")] pl_PL,
        [Description("Pashto")] ps,
        [Description("Pashto (Afghanistan)")] ps_AR,
        [Description("Portuguese")] pt,
        [Description("Portuguese (Brazil)")] pt_BR,
        [Description("Portuguese (Portugal)")] pt_PT,
        [Description("Quechua")] qu,
        [Description("Quechua (Bolivia)")] qu_BO,
        [Description("Quechua (Ecuador)")] qu_EC,
        [Description("Quechua (Peru)")] qu_PE,
        [Description("Romanian")] ro,
        [Description("Romanian (Romania)")] ro_RO,
        [Description("Russian")] ru,
        [Description("Russian (Russia)")] ru_RU,
        [Description("Sanskrit")] sa,
        [Description("Sanskrit (India)")] sa_IN,
        [Description("Sami")] se,
        [Description("Sami (Finland)")] se_FI,
        [Description("Sami (Norway)")] se_NO,
        [Description("Sami (Sweden)")] se_SE,
        [Description("Slovak")] sk,
        [Description("Slovak (Slovakia)")] sk_SK,
        [Description("Slovenian")] sl,
        [Description("Slovenian (Slovenia)")] sl_SI,
        [Description("Albanian")] sq,
        [Description("Albanian (Albania)")] sq_AL,
        [Description("Serbian (Latin) (Bosnia and Herzegovina)")] sr_BA,
        [Description("Serbian (Cyrillic) (Bosnia and Herzegovina)")] sr_Cyrl_BA,
        [Description("Serbian (Latin) (Serbia and Montenegro)")] sr_SP,
        [Description("Serbian (Cyrillic) (Serbia and Montenegro)")] sr_Cyrl_SP,
        [Description("Swedish")] sv,
        [Description("Swedish (Finland)")] sv_FI,
        [Description("Swedish (Sweden)")] sv_SE,
        [Description("Swahili")] sw,
        [Description("Swahili (Kenya)")] sw_KE,
        [Description("Syriac")] syr,
        [Description("Syriac (Syria)")] syr_SY,
        [Description("Tamil")] ta,
        [Description("Tamil (India)")] ta_IN,
        [Description("Telugu")] te,
        [Description("Telugu (India)")] te_IN,
        [Description("Thai")] th,
        [Description("Thai (Thailand)")] th_TH,
        [Description("Tagalog")] tl,
        [Description("Tagalog (Philippines)")] tl_PH,
        [Description("Tswana")] tn,
        [Description("Tswana (South Africa)")] tn_ZA,
        [Description("Turkish")] tr,
        [Description("Turkish (Turkey)")] tr_TR,
        [Description("Tatar")] tt,
        [Description("Tatar (Russia)")] tt_RU,
        [Description("Tsonga")] ts,
        [Description("Ukrainian")] uk,
        [Description("Ukrainian (Ukraine)")] uk_UA,
        [Description("Urdu")] ur,
        [Description("Urdu (Islamic Republic of Pakistan)")] ur_PK,
        [Description("Uzbek (Latin)")] uz,
        [Description("Uzbek (Latin) (Uzbekistan)")] uz_UZ,
        [Description("Uzbek (Cyrillic) (Uzbekistan)")] uz_Cyrl_UZ,
        [Description("Vietnamese")] vi,
        [Description("Vietnamese (Viet Nam)")] vi_VN,
        [Description("Xhosa")] xh,
        [Description("Xhosa (South Africa)")] xh_ZA,
        [Description("Chinese")] zh,
        [Description("Chinese (Simplified)")] zh_CN,
        [Description("Chinese (Hong Kong)")] zh_HK,
        [Description("Chinese (Macau)")] zh_MO,
        [Description("Chinese (Singapore)")] zh_SG,
        [Description("Chinese (Traditional)")] zh_TW,
        [Description("Zulu")] zu,
        [Description("Zulu (South Africa)")] zu_ZA
    }
}